// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbuhraMQIqrCi8Qc3aoibCe6inY7ouZ38',
    appId: '1:424019011568:web:58b3ad0474f0e28a829f35',
    messagingSenderId: '424019011568',
    projectId: 'portal-berita-app-1',
    authDomain: 'portal-berita-app-1.firebaseapp.com',
    storageBucket: 'portal-berita-app-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ5NI8dSKj49Z3zLTSLHEV9CJGhQbd62Y',
    appId: '1:424019011568:android:09517c56c852c3a9829f35',
    messagingSenderId: '424019011568',
    projectId: 'portal-berita-app-1',
    storageBucket: 'portal-berita-app-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9deHAOP0bFrHPO4pKFsiGSOEjd_Gt5U',
    appId: '1:424019011568:ios:22b906d6cf06be15829f35',
    messagingSenderId: '424019011568',
    projectId: 'portal-berita-app-1',
    storageBucket: 'portal-berita-app-1.firebasestorage.app',
    iosBundleId: 'com.example.portalBeritaFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH9deHAOP0bFrHPO4pKFsiGSOEjd_Gt5U',
    appId: '1:424019011568:ios:22b906d6cf06be15829f35',
    messagingSenderId: '424019011568',
    projectId: 'portal-berita-app-1',
    storageBucket: 'portal-berita-app-1.firebasestorage.app',
    iosBundleId: 'com.example.portalBeritaFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbuhraMQIqrCi8Qc3aoibCe6inY7ouZ38',
    appId: '1:424019011568:web:9471e17a84390149829f35',
    messagingSenderId: '424019011568',
    projectId: 'portal-berita-app-1',
    authDomain: 'portal-berita-app-1.firebaseapp.com',
    storageBucket: 'portal-berita-app-1.firebasestorage.app',
  );
}
